---
spring:
  config:
    activate:
      on-profile: "mysql"
  datasource:
    url: jdbc:mysql://localhost:3306/birthday
    username: birthday_user
    password: birthday_password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC