---
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:birthday}
    username: ${DATABASE_USER:birthday_user}
    password: ${DATABASE_PASS:birthday_password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:h2:mem:birthday
    username: local
    password: localpass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.h2.Driver
        jdbc:
          time_zone: UTC
