---
name: ci

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Gradle build
        run: ./gradlew build --no-daemon

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: build/reports/
          